server:
  port: 5001


spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: ${dbusername}
    password: ${dbpassword}
  jpa:
    show-sql: true
    properties:
      eclipselink.weaving: static
      eclipselink.ddl-generation: none
      eclipselink.logging.timestamp: false
      eclipselink.logging.session: false
      eclipselink.logging.connection: false
      eclipselink.logging.thread: false
      eclipselink.logging.level.sql: FINE
      eclipselink.logging.parameters: true